name: Build Linux Wheel

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install wheel setuptools  # Added setuptools here

      - name: Build the C extension
        run: python setup.py bdist_wheel

      - name: Upload the wheel file
        uses: actions/upload-artifact@v4
        with:
          name: linux-wheel
          path: dist/*.whl